import Redis from 'ioredis';
import crypto from 'crypto';

/**
 * PHI Token Vault (HIPAA-Compliant Tokenization)
 * 
 * Intercepts text payload and scrubs PHI/PII via RegEx. 
 * Instead of completely destroying the data, it generates secure, ephemeral tokens
 * (e.g. {{EMAIL_A9B2C3}}) and stores the mapping in Redis with a strict Time-to-Live (TTL).
 * 
 * Once the LLM completes its generation using the tokens, the orchestrator invokes 
 * the restore() function to map the tokens back to real data before executing the final action.
 */
export class PhiTokenVault {
  private redis: Redis;
  private ttlSeconds = 300; // Strictly 5 minutes TTL for PHI

  constructor() {
    this.redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');
  }

  /**
   * Scans text for PHI, replaces it with secure tokens, and stores the mapping in Redis.
   * @param text The raw prompt containing PHI
   * @returns scrubbedText (safe for LLMs) and a sessionId (to retrieve the tokens later)
   */
  async scrubAndStore(text: string): Promise<{ scrubbedText: string, sessionId: string }> {
    let scrubbed = text;
    const sessionId = crypto.randomUUID();
    const tokenMap: Record<string, string> = {};

    const replaceAndStore = (regex: RegExp, prefix: string) => {
      scrubbed = scrubbed.replace(regex, (match) => {
        // Generate a random 8-character hex token identifier
        const token = `{{${prefix}_${crypto.randomBytes(4).toString('hex').toUpperCase()}}}`;
        tokenMap[token] = match;
        return token;
      });
    };

    // 1. Mask Social Security Numbers (SSN)
    replaceAndStore(/\b\d{3}[-.]?\d{2}[-.]?\d{4}\b/g, 'SSN');
    
    // 2. Mask Email Addresses
    replaceAndStore(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, 'EMAIL');
    
    // 3. Mask Phone Numbers (Standard US)
    replaceAndStore(/\b(?:\+?1[-.]?)?\(?([0-9]{3})\)?[-.]?([0-9]{3})[-.]?([0-9]{4})\b/g, 'PHONE');

    // 4. Mask Medicare / Health Plan Identifiers
    replaceAndStore(/\b[A-Z0-9]{8,12}\b/g, (match) => {
      return /^[A-Z]+$/.test(match) ? match : `{{HEALTH_ID_${crypto.randomBytes(4).toString('hex').toUpperCase()}}}`;
    });

    // Only hit Redis if we actually found PHI to tokenize
    if (Object.keys(tokenMap).length > 0) {
      await this.redis.set(`phi_vault:${sessionId}`, JSON.stringify(tokenMap), 'EX', this.ttlSeconds);
    }

    return { scrubbedText: scrubbed, sessionId };
  }

  /**
   * Scans the LLM's response for tokens and maps them back to the original PHI 
   * securely stored in Redis.
   * @param responseText The text generated by the LLM (containing tokens)
   * @param sessionId The unique ID generated during scrubAndStore()
   * @returns The restored text with real data.
   */
  async restore(responseText: string, sessionId: string): Promise<string> {
    const data = await this.redis.get(`phi_vault:${sessionId}`);
    
    if (!data) {
      // Data expired or no tokens were generated for this session
      return responseText;
    }

    const tokenMap = JSON.parse(data);
    let restored = responseText;
    
    // Iterate through all stored tokens and replace them in the LLM response
    for (const [token, originalValue] of Object.entries(tokenMap)) {
      // Escape the token string to safely use it in a global Regex replacement
      const tokenRegex = new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
      restored = restored.replace(tokenRegex, originalValue as string);
    }

    return restored;
  }
}
